name: Clean Core Deployments

on:
  push:
    branches:
      - "main"

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: 🗑 Delete deployments
        uses: strumwolf/delete-deployment-environment@v2
        with:
          token: ${{ secrets.NPM_TOKEN_CORE }}
          environment: production-core
          ref: ${{ github.ref_name }}
          onlyRemoveDeployments: true
