name: Publish React Package

on:
  push:
    tags:
      - "react@*"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    environment: production-react
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"

      - name: Install Package Manager
        run: yarn add --global pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Tests
        run: pnpm test

      - name: Build Package
        run: pnpm build

      - name: Publish react package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN_REACT }}
